C:\Users\Varsha\OneDrive\Desktop\Rasa Ai\venv\lib\site-packages\rasa\core\tracker_store.py:1044: MovedIn20Warning: Deprecated API features detected! These feature(s) are not compatible with SQLAlchemy 2.0. To prevent incompatible upgrades prior to updating applications, ensure requirements files are pinned to "sqlalchemy<2.0". Set environment variable SQLALCHEMY_WARN_20=1 to show all deprecation warnings.  Set environment variable SQLALCHEMY_SILENCE_UBER_WARNING=1 to silence this message. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base: DeclarativeMeta = declarative_base()
C:\Users\Varsha\OneDrive\Desktop\Rasa Ai\venv\lib\site-packages\rasa\shared\utils\validation.py:134: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
C:\Users\Varsha\OneDrive\Desktop\Rasa Ai\venv\lib\site-packages\pkg_resources\__init__.py:3117: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
C:\Users\Varsha\OneDrive\Desktop\Rasa Ai\venv\lib\site-packages\pkg_resources\__init__.py:3117: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
C:\Users\Varsha\OneDrive\Desktop\Rasa Ai\venv\lib\site-packages\sanic_cors\extension.py:39: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  SANIC_VERSION = LooseVersion(sanic_version)
2025-05-20 10:09:15 [1;30mDEBUG   [0m [34mh5py._conv[0m  - Creating converter from 7 to 5
2025-05-20 10:09:15 [1;30mDEBUG   [0m [34mh5py._conv[0m  - Creating converter from 5 to 7
2025-05-20 10:09:15 [1;30mDEBUG   [0m [34mh5py._conv[0m  - Creating converter from 7 to 5
2025-05-20 10:09:15 [1;30mDEBUG   [0m [34mh5py._conv[0m  - Creating converter from 5 to 7
2025-05-20 10:09:28 [1;30mDEBUG   [0m [34mjax._src.path[0m  - etils.epath was not found. Using pathlib for file I/O.
C:\Users\Varsha\OneDrive\Desktop\Rasa Ai\venv\lib\site-packages\tensorflow\lite\python\util.py:52: DeprecationWarning: jax.xla_computation is deprecated. Please use the AOT APIs.
  from jax import xla_computation as _xla_computation
No chat connector configured, falling back to the REST input channel. To connect your bot to another channel, read the docs here: https://rasa.com/docs/rasa/messaging-and-voice-channels
2025-05-20 10:09:40 [1;30mDEBUG   [0m [34mrasa.core.utils[0m  - Available web server routes: 
/conversations/<conversation_id:path>/messages     POST                           add_message
/conversations/<conversation_id:path>/tracker/events POST                           append_events
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id:path>/execute      POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id:path>/predict      POST                           predict
/conversations/<conversation_id:path>/tracker/events PUT                            replace_events
/conversations/<conversation_id:path>/story        GET                            retrieve_story
/conversations/<conversation_id:path>/tracker      GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id:path>/trigger_intent POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2025-05-20 10:09:40 [1;30mINFO    [0m [34mroot[0m  - Starting Rasa server on http://0.0.0.0:5006
2025-05-20 10:09:40 [1;30mDEBUG   [0m [34mrasa.core.utils[0m  - Using the default number of Sanic workers (1).
<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead
2025-05-20 10:09:40 [1;30mDEBUG   [0m [34mrasa.telemetry[0m  - Skipping telemetry reporting: no license hash found.
2025-05-20 10:09:40 [1;30mDEBUG   [0m [34mrasa.core.tracker_store[0m  - Connected to InMemoryTrackerStore.
2025-05-20 10:09:40 [1;30mDEBUG   [0m [34mrasa.core.lock_store[0m  - Connected to lock store 'InMemoryLockStore'.
2025-05-20 10:09:40 [1;30mDEBUG   [0m [34mrasa.core.nlg.generator[0m  - Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
[93mC:\Users\Varsha\OneDrive\Desktop\Rasa Ai\venv\lib\site-packages\rasa\shared\utils\io.py:99: UserWarning: No valid model found at models!
[0m2025-05-20 10:09:40 [1;30mINFO    [0m [34mroot[0m  - Rasa server is up and running.
[2025-05-20 10:09:40 +0530] [4924] [ERROR] Unable to start server
Traceback (most recent call last):
  File "C:\Users\Varsha\OneDrive\Desktop\Rasa Ai\venv\lib\site-packages\sanic\server\runners.py", line 133, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "C:\Users\Varsha\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "C:\Users\Varsha\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1493, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 5006): only one usage of each socket address (protocol/network address/port) is normally permitted
